import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Provider from "./components/Provider";

const geistSans = Geist({
   variable: "--font-geist-sans",
   subsets: ["latin"],
});

const geistMono = Geist_Mono({
   variable: "--font-geist-mono",
   subsets: ["latin"],
});

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default async function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
         >
            <Provider>
               <>
                  <Navbar />
                  {children}
               </>
            </Provider>

            {/* Footer */}
            <footer className="bg-gray-200 mt-16 py-10 px-2 sm:px-4">
               <div className="max-w-7xl mx-auto grid grid-cols-1 md:grid-cols-3 gap-8 text-sm text-gray-700 w-full">
                  {/* Customer Service */}
                  <div>
                     <div className="font-bold mb-3">Customer Service</div>
                     <ul className="space-y-2">
                        <li>
                           <a href="#" className="hover:underline">
                              Contact us
                           </a>
                        </li>
                        <li>
                           <a href="#" className="hover:underline">
                              FAQs
                           </a>
                        </li>
                        <li>
                           <a href="#" className="hover:underline">
                              Orders and delivery
                           </a>
                        </li>
                        <li>
                           <a href="#" className="hover:underline">
                              Returns and refunds
                           </a>
                        </li>
                        <li>
                           <a href="#" className="hover:underline">
                              Payment and pricing
                           </a>
                        </li>
                        <li>
                           <a href="#" className="hover:underline">
                              Cryptocurrency payments
                           </a>
                        </li>
                        <li>
                           <a href="#" className="hover:underline">
                              Promotion terms and conditions
                           </a>
                        </li>
                        <li>
                           <a href="#" className="hover:underline">
                              FARFETCH Customer Promise
                           </a>
                        </li>
                     </ul>
                  </div>
                  {/* About FARFETCH */}
                  <div>
                     <div className="font-bold mb-3">About FARFETCH</div>
                     <ul className="space-y-2">
                        <li>
                           <a href="#" className="hover:underline">
                              About us
                           </a>
                        </li>
                        <li>
                           <a href="#" className="hover:underline">
                              FARFETCH partner boutiques
                           </a>
                        </li>
                        <li>
                           <a href="#" className="hover:underline">
                              Careers
                           </a>
                        </li>
                        <li>
                           <a href="#" className="hover:underline">
                              FARFETCH app
                           </a>
                        </li>
                        <li>
                           <a href="#" className="hover:underline">
                              Modern slavery statement
                           </a>
                        </li>
                        <li>
                           <a href="#" className="hover:underline">
                              FARFETCH Advertising
                           </a>
                        </li>
                     </ul>
                  </div>
                  {/* Discounts and membership */}
                  <div>
                     <div className="font-bold mb-3">
                        Discounts and membership
                     </div>
                     <ul className="space-y-2">
                        <li>
                           <a href="#" className="hover:underline">
                              Affiliate program
                           </a>
                        </li>
                        <li>
                           <a href="#" className="hover:underline">
                              Refer a friend
                           </a>
                        </li>
                        <li>
                           <a href="#" className="hover:underline">
                              FARFETCH membership
                           </a>
                        </li>
                        <li>
                           <a href="#" className="hover:underline">
                              Student discount UNiDAYS
                           </a>
                        </li>
                        <li>
                           <a href="#" className="hover:underline">
                              Student Beans and Graduates
                           </a>
                        </li>
                        <li>
                           <a href="#" className="hover:underline">
                              Student and Youth discount
                           </a>
                        </li>
                     </ul>
                     <div className="mt-6">
                        <div className="font-bold mb-2">Follow us</div>
                        <div className="flex space-x-4 text-xl">
                           <a href="#" aria-label="Instagram">
                              <span className="fi fi-brands-instagram" />
                           </a>
                           <a href="#" aria-label="Facebook">
                              <span className="fi fi-brands-facebook" />
                           </a>
                           <a href="#" aria-label="Pinterest">
                              <span className="fi fi-brands-pinterest" />
                           </a>
                           <a href="#" aria-label="Twitter">
                              <span className="fi fi-brands-twitter" />
                           </a>
                           <a href="#" aria-label="Snapchat">
                              <span className="fi fi-brands-snapchat" />
                           </a>
                           <a href="#" aria-label="YouTube">
                              <span className="fi fi-brands-youtube" />
                           </a>
                        </div>
                     </div>
                  </div>
               </div>
            </footer>
         </body>
      </html>
   );
}
