import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
   variable: "--font-geist-sans",
   subsets: ["latin"],
});

const geistMono = Geist_Mono({
   variable: "--font-geist-mono",
   subsets: ["latin"],
});

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
         >
            <nav className="bg-white border-b border-gray-200 w-full">
               <div className="max-w-screen-xl mx-auto flex items-center justify-between py-4 px-8">
                  {/* Left menu - Search Input */}
                  <div className="flex items-center">
                     <form className="w-full">
                        <div className="flex items-center border-b border-gray-400 pb-1">
                           <svg
                              className="w-6 h-6 text-gray-400 mr-2"
                              aria-hidden="true"
                              xmlns="http://www.w3.org/2000/svg"
                              fill="none"
                              viewBox="0 0 24 24"
                           >
                              <circle
                                 cx="11"
                                 cy="11"
                                 r="8"
                                 stroke="currentColor"
                                 strokeWidth="2"
                              />
                              <path
                                 d="M21 21l-4.35-4.35"
                                 stroke="currentColor"
                                 strokeWidth="2"
                                 strokeLinecap="round"
                              />
                           </svg>
                           <input
                              type="search"
                              className="w-full outline-none bg-transparent text-gray-700 placeholder-gray-500 text-lg"
                              placeholder="What are you looking ?"
                           />
                        </div>
                     </form>
                  </div>

                  {/* Center logo */}
                  <div className="flex-1 flex justify-center">
                     <a
                        href="/"
                        className="text-4xl font-extrabold tracking-widest text-black select-none"
                     >
                        FARFATCH
                     </a>
                  </div>

                  {/* Right menu */}
                  <div className="flex items-center gap-6 min-w-[350px] justify-end">
                     {/* {name profile} */}
                     <div className="text-gray-800">
                        <a href="/profile">hello, John Doe</a>
                     </div>
                     {/* User icon */}
                     <a href="/profile" className="inline-flex items-center">
                        <svg
                           width="24"
                           height="24"
                           fill="none"
                           stroke="currentColor"
                           strokeWidth="2"
                           viewBox="0 0 24 24"
                           className="text-gray-700"
                        >
                           <circle cx="12" cy="8" r="4" />
                           <path d="M4 20c0-4 4-6 8-6s8 2 8 6" />
                        </svg>
                     </a>

                     <a href="/wishlist">
                        <svg
                           width="24"
                           height="24"
                           fill="none"
                           stroke="currentColor"
                           strokeWidth="2"
                           viewBox="0 0 24 24"
                           className="text-gray-700"
                        >
                           <path d="M12 21s-6.5-4.35-9-7.5C-1.5 8.5 3.5 3 8.5 7.5c2.5 2.25 3.5 2.25 6 0C20.5 3 25.5 8.5 21 13.5c-2.5 3.15-9 7.5-9 7.5z" />
                        </svg>
                     </a>
                     {/* Bag icon */}
                     <a href="/cart">
                        <svg
                           width="24"
                           height="24"
                           fill="none"
                           stroke="currentColor"
                           strokeWidth="2"
                           viewBox="0 0 24 24"
                           className="text-gray-700"
                        >
                           <rect x="4" y="7" width="16" height="13" rx="2" />
                           <path d="M8 7V5a4 4 0 1 1 8 0v2" />
                        </svg>
                     </a>
                     {/* {login / logout} */}
                     <Link href="/login">Login</Link>
                     <Link href="/register">Register</Link>
                  </div>
               </div>
            </nav>

            {children}
         </body>
      </html>
   );
}
